import type { Plan, Verdict } from "../verification/types";
import { botConfig } from "../../bot.config";

const tick = (b: boolean) => (b ? "✅" : "❌");
const warn = (b: boolean) => (b ? "✅" : "⚠️");

export function renderPrBody(args: {
  issue: { number: number; title: string; body: string };
  plan: Plan;
  verdict: Verdict;
  attempts: number;
  runId: number;
  costUsd: number;
  needsReview: boolean;
}): string {
  const v = args.verdict.checks;
  const head = args.needsReview
    ? "> [!WARNING]\n> This PR did not pass verification after the configured iteration budget. A human must read it carefully before merging.\n\n"
    : "";

  const editedTests = args.plan.tests_to_add_or_update.length
    ? args.plan.tests_to_add_or_update.map((t) => `\`${t.path}\``).join(", ")
    : "none";

  const editedFiles = args.plan.files_to_change.length
    ? args.plan.files_to_change.map((f) => `\`${f.path}\``).join(", ")
    : "none";

  const issueExcerpt = (args.issue.body ?? "")
    .slice(0, 200)
    .replace(/\n/g, "\n> ");

  const critic = v.critic.detail as
    | {
        merge_confidence?: number;
        one_line_summary?: string;
        missed_edge_cases?: string[];
      }
    | undefined;

  const edgeCases = critic?.missed_edge_cases ?? [];
  const edgeBlock = edgeCases.length
    ? edgeCases.map((e) => `- ${e}`).join("\n")
    : "_None flagged._";

  return `${head}## What changed
${args.plan.user_visible_change}

Closes #${args.issue.number}

## Why
${args.issue.title}

> ${issueExcerpt}

## Plan that was followed
- **Files changed:** ${editedFiles}
- **Tests added/updated:** ${editedTests}
- **Complexity:** ${args.plan.complexity}

## Verification report

| Check | Result |
|---|---|
| Typecheck | ${tick(v.typecheck.pass)} |
| Existing tests | ${tick(v.existing_tests.pass)} |
| New tests added per plan | ${tick(v.plan_tests_added.pass)} |
| Mutation-light (new tests fail pre / pass post) | ${tick(v.mutation_light.pass)} |
| Lint | ${warn(v.lint.pass)} |
| Diff size | ${warn(v.diff_size.pass)} |
| Banned patterns | ${tick(v.banned_patterns.pass)} |
| Critic confidence | ${critic?.merge_confidence ?? "—"}/100 |

**Critic summary:** ${critic?.one_line_summary ?? "—"}
${args.attempts > 1 ? `\n> _This PR took ${args.attempts} iteration(s) to pass verification._` : ""}

## Suggested human-review focus
${edgeBlock}

## Cost
$${args.costUsd.toFixed(4)} USD across ${args.attempts} attempts.

---
🤖 Generated by the 42n-bot. See [internal dashboard](${botConfig.dashboard.url}/runs/${args.runId}) for full event log.
`;
}
